name: Deploy to Staging
on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    name: Deploying Everything to the Staging Environment
    runs-on: ubuntu-latest
    steps:
      name: SSH into server
      run: |
        echo ${{secrets.SSH_PRIVATE_KEY}} &> ~/ssh_key
        ssh -i ~/ssh_key ubuntu@13.232.36.217
        cd Devops-1 && git pull 
        pnpm install
        pnpm run build
        pm2 restart fe-server
        pm2 restart http-server
        pm2 restart ws-server